export default {
    DEFAULT_TIMEOUT: 30000,
    FIRST_NAME_ERROR : 'we need your first name',
    ZIP_ERROR : 'which zip?',
    LAST_NAME_ERROR  : 'we need your last name',
    ADDRESS_ERROR : 'we need your address',
    CITY_ERROR : 'we need your city',
    STATE_ERROR : 'which state?',
    PHONE_ERROR : 'we need your phone number',
    EMAIL_ERROR : 'we need your email address',
    CONFIRM_EMAIL_ERROR : 'the email addresses don’t match',
    DOB_ERROR : 'we need to know your birthday',
    GENDER_ERROR : 'please select one',
    DEVICE_SUBS_URL : 'https://www.blinkfitness.com/join/murray-hill/green?icmp=Join_Now_Desription',
    WEB_SUBS_URL : 'https://www.blinkfitness.com/join/boerum-hill/green?icmp=Join_Now_Desription',
    BLUE_MEMBERSHIP : 'blue',
    GREEN_MEMBERSHIP : 'green',
    GRAY_MEMBERSHIP : 'gray',
}